apiVersion: v2
name: sample-api
description: Um chart wrapper para fazer o deploy do sample-api.
type: application
version: 0.1.0

dependencies:
  - name: generic-app
    version: "0.0.17"
    repository: "https://charts.visonneau.fr"
